// SPDX-License-Identifier: Apache-2.0
// Copyright 2024 Canonical Ltd.

 package authentication

 import (
	 "net/http"
 
	 "github.com/gin-gonic/gin"
 )
 
 // Route is the information for every URI.
 type Route struct {
	 // Name is the name of this Route.
	 Name string
	 // Method is the string for the HTTP method. ex) GET, POST etc..
	 Method string
	 // Pattern is the pattern of the URI.
	 Pattern string
	 // HandlerFunc is the handler function of this route.
	 HandlerFunc gin.HandlerFunc
 }
 
 // Routes is the list of the generated Route.
 type Routes []Route
 
 // This function is not autogenerated
 func AddService(engine *gin.Engine) *gin.RouterGroup {
	 group := engine.Group("/")
 
	 for _, route := range routes {
		 switch route.Method {
		 case "GET":
			 group.GET(route.Pattern, route.HandlerFunc)
		 case "POST":
			 group.POST(route.Pattern, route.HandlerFunc)
		 case "PUT":
			 group.PUT(route.Pattern, route.HandlerFunc)
		 case "DELETE":
			 group.DELETE(route.Pattern, route.HandlerFunc)
 
		 }
	 }
	 return group
 }
 
 // Index is the index handler.
 func Index(c *gin.Context) {
	 c.String(http.StatusOK, "Hello World!")
 }
 
 var routes = Routes{
	{
		"Index",
		http.MethodGet,
		"/",
		Index,
	},
	{
		"GetUserAccounts",
		http.MethodGet,
		"/account",
		GetUserAccounts,
	},
	{
		"GetUserAccount",
		http.MethodGet,
		"/account/:id",
		GetUserAccount,
	},
	{
		"PostUserAccount",
		http.MethodPost,
		"/account/:id",
		PostUserAccount,
	},
	{
		"DeleteUserAccount",
		http.MethodDelete,
		"/account/:id",
		DeleteUserAccount,
	},
	{
		"ChangeUserAccountPasssword",
		http.MethodPost,
		"/account/:id/change_password",
		ChangeUserAccountPasssword,
	},
	{
		"Login",
		http.MethodPost,
		"/login",
		Login,
	},
 }